### ISSUE TITLE
Clear search icon is missing on member's search field

### ISSUE THREAD

**Issue by juliechoudhary201** [bigbinary/neeto-team-members#47]
Ref: 
- https://github.com/bigbinary/neeto-form-web/issues/2288#issuecomment-1041439524
- https://github.com/bigbinary/neeto-runner-web/issues/1483

Open the neetoForm-> Members.

- **Clear search icon is missing on the search field.**

![image](https://user-images.githubusercontent.com/70018083/154269148-3a4452d3-1265-46cb-98bf-e78397ac1bb8.png)

**Comment by Thejus-Paul** [comment]
@Thejus-Paul _a
